version: '3'
services:
  sparklab:
    image: sparklab:latest
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workdir:/workdir
    env_file:
      - .env
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    ports:
      - 8888:8888